---
title: 'Learning behaviours aligned with moral values in a multi-agent system: guiding reinforcement learning with symbolic judgments'
author: 'Rémy Chaput'
date: '27/10/2022'

# Thesis information
title_fr: "Apprendre des comportements alignés sur des valeurs morales dans un système multi-agent: guider l'apprentissage par renforcement avec des jugements symboliques"
nnt: '2022LYO1071'
institution: "L'UNIVERSITÉ CLAUDE BERNARD LYON 1"
department: 'Informatique'
ednumber: '512'
edname: 'InfoMaths'
privacy: 'publiquement'

knit: bookdown::render_book
site: bookdown::bookdown_site

# This will automatically install the {remotes} package and {thesisdown}
# Change this to FALSE if you'd like to install them manually on your own.
params:
  'Install needed packages': True

# If you are creating a PDF you'll need to write your preliminary content 
# (e.g., abstract, acknowledgements) below or use code similar to line 25-26 
# for the .RMD files. If you are NOT producing a PDF, delete or silence
# lines 25-39 in this YAML header.
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "00-abstract.Rmd")), collapse = "\n  ")`
abstract_fr: |
  `r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "00-abstract-fr.Rmd")),
  collapse = "\n  ")`
summary_fr: |
  `r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "00-summary-fr.Rmd")), collapse = "\n  ")`
acknowledgements: |
  `r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "00-acknowledgments.Rmd")), collapse = "\n  ")`
# dedication: |
#   You can have a dedication here if you wish.
# preface: |
#   This is an example of a thesis setup to use the reed thesis document class.

# Specify the location of the bibliography below
bibliography: references.bib
# Download your specific csl file and refer to it in the line below.
csl: csl/apa.csl
# Add links to citations in the HTML output
link-citations: true
---


```{r include_packages, include=FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.

helper_install_pkg <- function (pkg.name, repos = "https://cran.rstudio.com") {
  if (!require(pkg.name, character.only = TRUE)) {
    if (params$`Install needed packages`) {
      install.packages(pkg.name, repos = repos)
      library(pkg.name, character.only = TRUE)
    } else {
      stop(
        paste0(
          "You need to run install.packages('", 
          pkg.name, 
          "') first in the R Console."
          )
        )
    }
  }
}

helper_install_github <- function (pkg.name, repo.name) {
  if (!require(pkg.name, character.only = TRUE)) {
    if (params$`Install needed packages`) {
      remotes::install_github(repo.name)
      library(pkg.name, character.only = TRUE)
    } else {
      stop(
        paste0(
          "You need to run remotes::install_github('",
          repo.name,
          "') first in the R Console."
        )
      )
    }
  }
}

helper_install_pkg("remotes")
helper_install_pkg("knitr")
helper_install_pkg("bookdown")
helper_install_pkg("tibble")
helper_install_pkg("dplyr")
helper_install_pkg("tidyr")
# For the algorithms engine, converting svg to pdf
helper_install_pkg("magick")
helper_install_pkg("pdftools")
# Improve the styling of tables
helper_install_pkg("kableExtra")
helper_install_pkg("flextable")
# For Python engine
helper_install_pkg("reticulate")
# For plots
helper_install_pkg("ggplot2")

helper_install_github("thesisdown", "ismayc/thesisdown")
helper_install_github("knitrdrawio", "rchaput/knitrdrawio")
helper_install_github("acronymsdown", "rchaput/acronymsdown")

```

```{r setup, include=FALSE}
# Avoid printing the source code of chunks, messages, and warnings
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
# Change LaTeX settings for float behaviour, i.e., placement of figures.
knitr::opts_chunk$set(fig.pos = "htbp")
# Set how wide the R output will go
options(width = 70)
# Setup Python engine
reticulate::use_virtualenv(file.path(getwd(), ".venv"))
# Ignore fonts in flextable (needs to use xelatex otherwise)
flextable::set_flextable_defaults(fonts_ignore = TRUE)
# Set the number of LaTeX compilations; this seems necessary to correctly
# build the Table of Contents. Without it, wrong page numbers are used.
options(tinytex.compile.min_times = 3)
```

```{python setup-python}
import seaborn as sns
palette = sns.color_palette()
# We set here the colors for our different models, to assure coherence
# throughout the manuscript.
models_colors = {
  'QSOM': palette[0],
  'Q-SOM-1': palette[0],
  'Q-SOM': palette[0],
  'QDSOM': palette[1],
  'Q-DSOM': palette[1],
  'Q-DSOM-1': palette[1],
  'DDPG': palette[2],
  'MADDPG': palette[3],
}
```

```{r setup-algorithm-engine, include=FALSE}
# From marcishak (https://github.com/rstudio/bookdown/issues/1292#issuecomment-991575445)
algorithm.engine <- function (options) {
  if (!options$eval) {
    return(engine_output(options, options$code, ""))
  }

  # wrap in algorithm
  options$fig.env <- "algorithm"
  options$fig.align <- "default"
  options$fig.lp <- "fig:" # alg doesn't work!!

  # stuff from knitr
  `%n%` <- function(x, y) if (is.null(x)) y else x

  # template
  # H required to work in standalone...
  lines <- r"(\documentclass{standalone}
  \usepackage{amsmath}
  \usepackage{amssymb}
  \usepackage{amsfonts}
  \usepackage{physics}  % For the `norm` command
  \usepackage{xcolor}  % For colored comments
  \input{maths.tex}  % Custom math definitions
  %% EXTRA_PREAMBLE_CODE %%
  \usepackage[
  %% ALGO_CLASSOPTION %%
  ]{algorithm2e}
  \begin{document}
  \begin{algorithm}[H]
  %% ALGO_CODE %%
  \end{algorithm}
  \end{document}
  )"

  lines <- unlist(strsplit(lines, "\n"))

  options$resize.width <- NULL
  options$resize.height <- NULL
  options$resize.command <- NULL

  # add class options to template
  lines <- knitr:::insert_template(
    lines, "%% ALGO_CLASSOPTION %%", "linesnumbered,vlined", F
  )
  # insert code into preamble
  lines <- knitr:::insert_template(
    lines, "%% EXTRA_PREAMBLE_CODE %%", options$engine.opts$extra.preamble, F
  )

  options$fig.cap <- if (knitr::is_html_output() && !(grepl("(A|a)lgorithm", options$fig.cap))) {
    paste(options$fig.cap, "algorithm")
  } else {
    options$fig.cap
  }

  # insert tikz code into the tex template
  lines <- knitr:::insert_template(lines, "%% ALGO_CODE %%", options$code)
  xfun::write_utf8(lines, texf <- knitr:::wd_tempfile("tikz", ".tex"))
  on.exit(unlink(texf), add = TRUE)

  ext <- tolower(options$fig.ext %n% knitr:::dev2ext(options))

  to_svg <- ext == "svg"
  outf <- if (to_svg) tinytex::latexmk(texf, "latex") else tinytex::latexmk(texf)

  fig <- knitr:::fig_path(if (to_svg) ".dvi" else ".pdf", options)
  dir.create(dirname(fig), recursive = TRUE, showWarnings = FALSE)
  file.rename(outf, fig)

  fig2 <- xfun:::with_ext(fig, ext)
  if (to_svg) {
    # dvisvgm needs to be on the path
    # dvisvgm for windows needs ghostscript bin dir on the path also
    if (Sys.which("dvisvgm") == "") tinytex::tlmgr_install("dvisvgm")
    if (system2("dvisvgm", c(
      options$engine.opts$dvisvgm.opts, "-o", shQuote(fig2), fig
    )) != 0) {
      stop("Failed to compile ", fig, " to ", fig2)
    }
  } else {
    # convert to the desired output-format using magick
    if (ext != "pdf") {
      magick::image_write(do.call(magick::image_convert, c(
        list(magick::image_read_pdf(fig), ext), options$engine.opts$convert.opts
      )), fig2)
    }
  }
  fig <- fig2

  options$engine <- "tikz" # pretend to be tikz
  options$fig.num <- 1L
  options$fig.cur <- 1L
  extra <- knitr:::run_hook_plot(fig, options)
  options$engine <- "tex" # for output hooks to use the correct language class
  knitr::engine_output(options, options$code, "", extra)
}

knitr::knit_engines$set(algorithm = algorithm.engine)
```


<!-- Required to number equations in HTML files -->
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

<!--
The acknowledgments, preface, dedication, and abstract are added into the PDF
version automatically by inputting them in the YAML at the top of this file.
Alternatively, you can put that content in files like 00--prelim.Rmd and
00-abstract.Rmd like done below.
-->


```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "00--prelim.Rmd")}

```

`r if(!knitr:::is_latex_output()) '## Abstract {-}'`

```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "00-abstract.Rmd")}

```

`r if(!knitr:::is_latex_output()) '## Résumé (Fr) {-}'`

```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "00-abstract-fr.Rmd")}

```
